### ISSUE TITLE
Vivint Error Although System is Connected

### ISSUE THREAD

**Issue by OspreyBoat** [balansse/homebridge-vivint#116]
Version 1.8.3

My log is throwing the following error although it continues to operate.  On Fiber Optic Internet with Frontier.  Seems to be a busy signal?

Thanks
____________________

Vivint BridgeVivintERRORError getting system info: RequestError: Error: getaddrinfo EBUSY www.vivintsky.com
    at new RequestError (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/lib/hoobs/vivintbridge/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/var/lib/hoobs/vivintbridge/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: Error: getaddrinfo EBUSY www.vivintsky.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
    errno: -16,
    code: 'EBUSY',
    syscall: 'getaddrinfo',
    hostname: 'www.vivintsky.com'
  },
  error: Error: getaddrinfo EBUSY www.vivintsky.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
    errno: -16,
    code: 'EBUSY',
    syscall: 'getaddrinfo',
    hostname: 'www.vivintsky.com'
  },
  options: {
    url: 'https://www.vivintsky.com/api/systems/NUMBER REDACTED',
    headers: {
      Cookie: 'REDACTED',
      'Cache-Control': 'no-store'
    },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

**Comment by jgrimard** [comment]
It looks similar to this one. Some sort of bug in HOOBS?  
https://github.com/balansse/homebridge-vivint/issues/116#issue-comment-box

**Comment by OspreyBoat** [comment]
Thanks - just posted at HOOBS work site
