### ISSUE TITLE
bootstrapping

### ISSUE THREAD

**Issue by ryannoble4505** [balansse/homebridge-vivint#149]
Error while bootstrapping accessories: TypeError: Cannot read properties of undefined (reading 'SECURITY_SYSTEM')
    at Function.inferCategory (/usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/panel.js:107:35)
    at Function.createDeviceAccessory (/usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/device_set.js:135:63)
    at /usr/local/lib/node_modules/@balansse/homebridge-vivint/index.js:55:50
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/@balansse/homebridge-vivint/index.js:55:20
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by jgrimard** [comment]
FYI, is a Homebridge 2.0 error

**Comment by meek2100** [comment]
@ryannoble4505, 
Is this resolved with the changes @jgrimard  made to support HomeBridge 2.0 with v1.10.0?

**Comment by ryannoble4505** [comment]
Yes, thanks Sent from my iPhoneOn Mar 3, 2025, at 2:43 PM, meek2100 ***@***.***> wrote:﻿
  @ryannoble4505,
Is this resolved with the changes @jgrimard  made to support HomeBridge 2.0 with v1.10.0?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



meek2100 left a comment (balansse/homebridge-vivint#149)
@ryannoble4505,
Is this resolved with the changes @jgrimard  made to support HomeBridge 2.0 with v1.10.0?
