### ISSUE TITLE
API Authentication Issue Started October 2024

### ISSUE THREAD

**Issue by ffemt-asher** [balansse/homebridge-vivint#161]
I have tried a few different things to get this fixed. I refreshed the token, reinstalled the bridge and made sure all updates have been installed. This is the error I am seeing in the homebride log.

[11/1/2024, 5:25:26 PM] [@balansse/homebridge-vivint] Error occurred during login, retrying in 60 seconds... StatusCodeError: 401 - "\r\n<title>401 Authorization Required</title>\r\n\r\n
401 Authorization Required
\r\nnginx\r\n\r\n\r\n"
at new StatusCodeError (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request-promise-core/lib/errors.js:32:15)
at Request.plumbing.callback (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request-promise-core/lib/plumbing.js:104:33)
at Request.RP$callback [as _callback] (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request-promise-core/lib/plumbing.js:46:31)
at Request.self.callback (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request/request.js:185:22)
at Request.emit (node:events:518:28)
at Request. (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request/request.js:1154:10)
at Request.emit (node:events:518:28)
at IncomingMessage. (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request/request.js:1076:12)
at Object.onceWrapper (node:events:632:28)
at IncomingMessage.emit (node:events:530:35) {
statusCode: 401,
error: '\r\n' +
'<title>401 Authorization Required</title>\r\n' +
'\r\n' +
'
401 Authorization Required
\r\n' +
'nginx\r\n' +
'\r\n' +
'\r\n',

**Comment by dtheurer-control4** [comment]
@ffemt-asher, 
Are you a Telus customer in Canada?  I know Telus bought out Vivint Canada and took account ownership of those accounts which I believe changed the authentication path for those customers since it broke people's Home Assistant integration.

https://support.vivint.com/article/TELUS-Acquisition-of-Vivint-Canada-FAQ

**Comment by ffemt-asher** [comment]
@balansse I am based out of Utah, so that shouldn’t have affected me.

**Comment by ffemt-asher** [comment]
@balansse i was able to get this to work. Theses are my steps. I reverted the version of the bridge to 1.8.0, refreshed the token for Vivint. It errored out with a different error, then I re-installed the 1.9.0 update and refreshed the token again and that did the trick.
