### ISSUE TITLE
Error in HomeBridge

### ISSUE THREAD

**Issue by mlittle408** [balansse/homebridge-vivint#17]
Everything has been working fine until today. I see this in the logfile:

Error: The requested platform 'Vivint' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at config.platforms.forEach (/usr/local/lib/node_modules/homebridge/src/server.ts:387:37)
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

I've tried removing and reinstalling the plugin, rebooting the Vivint Skypanel  and the homebridge server without success.

**Comment by mlittle408** [comment]
Here's the entire log:

[1/17/2021, 10:02:45 PM] [Homebridge UI] Changes to config.json saved.
[1/17/2021, 10:02:47 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/17/2021, 10:02:50 PM] [Homebridge UI] Homebridge restart request received
[1/17/2021, 10:02:50 PM] [Homebridge UI] No restart command defined, killing process...
[1/17/2021, 10:02:50 PM] [HB Supervisor] Stopping services...
[1/17/2021, 10:02:52 PM] [HB Supervisor] Restarting Homebridge...
[1/17/2021, 10:02:52 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[1/17/2021, 10:02:52 PM] [HB Supervisor] Started Homebridge v1.1.7 with PID: 1815
[1/17/2021, 10:02:53 PM] Loaded config.json with 0 accessories and 2 platforms.
[1/17/2021, 10:02:53 PM] ---
[1/17/2021, 10:02:53 PM] Loaded plugin: homebridge-config-ui-x@4.36.0
[1/17/2021, 10:02:53 PM] Registering platform 'homebridge-config-ui-x.config'
[1/17/2021, 10:02:53 PM] ---
[1/17/2021, 10:02:54 PM] ====================
[1/17/2021, 10:02:54 PM] ERROR LOADING PLUGIN @balansse/homebridge-vivint:
[1/17/2021, 10:02:54 PM] /usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/thermostat.js:309
    fahrenheitToCelsius = function(temperature) {
                        ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/device_set.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[1/17/2021, 10:02:54 PM] ====================
[1/17/2021, 10:02:54 PM] Loading 2 platforms...
[1/17/2021, 10:02:54 PM] [Config] Initializing config platform...
[1/17/2021, 10:02:54 PM] [Config] Running in Service Mode
[1/17/2021, 10:02:54 PM] Error loading platform requested in your config.json at position 2
[1/17/2021, 10:02:54 PM] Error: The requested platform 'Vivint' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at config.platforms.forEach (/usr/local/lib/node_modules/homebridge/src/server.ts:387:37)
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
[1/17/2021, 10:02:54 PM] Got SIGTERM, shutting down Homebridge...
[1/17/2021, 10:03:02 PM] [HB Supervisor] OS: Linux 4.19.0-13-686 ia32
[1/17/2021, 10:03:02 PM] [HB Supervisor] Node.js v10.21.0 /usr/bin/node
[1/17/2021, 10:03:02 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[1/17/2021, 10:03:02 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[1/17/2021, 10:03:02 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[1/17/2021, 10:03:02 PM] [HB Supervisor] Started Homebridge v1.1.7 with PID: 1866
[1/17/2021, 10:03:03 PM] Loaded config.json with 0 accessories and 2 platforms.

**Comment by mlittle408** [comment]
Sorry, I was running 1.4.1, I just rolled back to 1.3.1 and it's working fine again.

**Comment by balansse** [comment]
I wasn't able to reproduce this issue on my setup, it looks like it might be related to NodeJS version: v10.21.0 in your log file vs v14.15.3 on my local machine. 

I'll look into simplifying that part in the next minor update so it won't require a higher NodeJS version.

**Comment by mlittle408** [comment]
Thanks for the response. Looking forward to the update. Thanks a bunch for the really useful plugin!!!

**Comment by balansse** [comment]
Please update to the latest 1.4.1 and let me know!

**Comment by mlittle408** [comment]
It's still showing 1.4.0 as the current version. As soon as 1.4.1 is ready I'll grab it and test it.

**Comment by mlittle408** [comment]
Updated and it's working just fine. FYI, I use homebridge and your plugin for use in Home Assistant. Thanks for fixing the issue!!
