### ISSUE TITLE
Plugin crashes on HomeBridge 1.3 branch

### ISSUE THREAD

**Issue by vcdx71** [balansse/homebridge-vivint#18]
I attempted to test the latest 1.3 HomeBridge release but ran into an issue with this plugin. All Vivint devices go into not responding and this shows up in the log.

    (node:7300) UnhandledPromiseRejectionWarning: Error: characteristic value expected number and received object
    at Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1859:17)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1428:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at Panel.getTargetState (/usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/panel.js:67:14)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/panel.js:52:43)
    at Characteristic.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1404:14
    at new Promise (<anonymous>)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1402:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    (node:7300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by balansse** [comment]
Homebridge 1.3.0 is still in beta stage - please report all issues to the Homebridge beta 1.3.0 thread https://github.com/homebridge/homebridge/issues/2765

**Comment by vcdx71** [comment]
That thread says to report issues with plugins to the plug in developer.

**Comment by balansse** [comment]
Please check out the latest plugin update, this should be fixed in 1.4.2

**Comment by vcdx71** [comment]
> Please check out the latest plugin update, this should be fixed in 1.4.2

Awesome, thanks! Looks good!
