### ISSUE TITLE
Errors after updating

### ISSUE THREAD

**Issue by mlittle408** [balansse/homebridge-vivint#24]
I'm getting this error after updating the plugin to the latest version.

[3/16/2021, 8:35:27 AM] [Vivint] Handling camera snapshot for 'Living Room' at 640x480
[3/16/2021, 8:35:27 AM] [Vivint] TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:545:16)
    at Camera.handleSnapshotRequest (/usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/camera.js:191:17)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:436:23
    at new Promise (<anonymous>)
    at CameraController.handleSnapshotRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:420:12)
    at Bridge.Accessory.handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1781:18)
    at HAPServer.emit (events.js:198:13)
    at HAPServer.handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:968:12)

**Comment by balansse** [comment]
What Homebridge version do you use?

**Comment by mlittle408** [comment]
Well, that's funny. I'm now running 1.3.3 and the problem is gone. My apologies, I thought I was running the latest version. Have a great day.

**Comment by mlittle408** [comment]
Sorry. I spoke to soon. The problem is still there. 

[3/16/2021, 11:17:55 AM] [Vivint] TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:545:16)
    at Camera.handleSnapshotRequest (/usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/camera.js:191:17)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:436:23
    at new Promise (<anonymous>)
    at DoorbellController.CameraController.handleSnapshotRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:420:12)
    at Bridge.Accessory.handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1781:18)
    at HAPServer.emit (events.js:198:13)
    at HAPServer.handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:968:12)

**Comment by balansse** [comment]
Can you run Homebridge in DEBUG mode and [send](mailto:balansse@gmail.com) me your logs starting from the start of Homebridge and up to the error?

**Comment by mlittle408** [comment]
Sent

**Comment by balansse** [comment]
It looks like the ffmpeg dependency was not installed correctly. Have you tried reinstalling Vivint plugin after the Homebridge update?

**Comment by mlittle408** [comment]
I just did and it's still failing.

Anything else I can try?

Mike

**Comment by balansse** [comment]
What platform do you run Homebridge on?

**Comment by mlittle408** [comment]
Linux

**Comment by mlittle408** [comment]
Sorry Raspberry pi on an oracle VM. Debian

**Comment by balansse** [comment]
Can you try manually installing ffmpeg like this:

sudo curl -Lf# https://github.com/homebridge/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-raspbian-armv6l.tar.gz | sudo tar xzf - -C / --no-same-owner

**Comment by mlittle408** [comment]
I was able to install it but it didn't fix the problem.

**Comment by balansse** [comment]
Please update to the latest version and let me know! Should fix the issue you're having

**Comment by mlittle408** [comment]
The update resolve the initial issue. Thank you so much. I am getting a new error, though. 

[3/21/2021, 4:05:34 PM] [Vivint] Snapshot process exited with code 255
[3/21/2021, 4:05:35 PM] [Vivint] Snapshot process exited with code 255
[3/21/2021, 4:05:35 PM] [Vivint] Snapshot process exited with code 255
[3/21/2021, 4:05:36 PM] [Vivint] Snapshot process exited with code 255
[3/21/2021, 4:05:36 PM] [Vivint] Snapshot process exited with code 255
[3/21/2021, 4:05:38 PM] [Vivint] Snapshot process exited with code 255
[3/21/2021, 4:05:38 PM] [Vivint] Snapshot process exited with code 255

**Comment by mlittle408** [comment]
I reinstalled HomeBridge to a new machine, installed the latest version and everything is working fine now. Thanks!
