### ISSUE TITLE
Vivint/MYQ garage door target state won't close

### ISSUE THREAD

**Issue by 007GTCS** [balansse/homebridge-vivint#35]
If I use the garage door controller through vivint homebridge. The garage door will not open or update status correctly. Vivint app works just fine. 

Logs Below:
[8/29/2021, 8:30:38 PM] [@balansse/homebridge-vivint] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[8/29/2021, 8:31:48 PM] [@balansse/homebridge-vivint] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[8/29/2021, 8:31:57 PM] [@balansse/homebridge-vivint] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[8/29/2021, 8:43:50 PM] [@balansse/homebridge-vivint] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://git.io/JtMGR for more info.
(node:629350) UnhandledPromiseRejectionWarning: ReferenceError: log is not defined
    at /usr/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/garage_door.js:33:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:629350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:629350) UnhandledPromiseRejectionWarning: ReferenceError: log is not defined
    at /usr/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/garage_door.js:33:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:629350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:629350) UnhandledPromiseRejectionWarning: ReferenceError: log is not defined
    at /usr/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/garage_door.js:33:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:629350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
[8/29/2021, 8:44:38 PM] [@balansse/homebridge-vivint] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://git.io/JtMGR for more info.
(node:629350) UnhandledPromiseRejectionWarning: ReferenceError: log is not defined
    at /usr/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/garage_door.js:33:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:629350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
[8/29/2021, 8:44:58 PM] [@balansse/homebridge-vivint] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[8/29/2021, 8:45:29 PM] [@balansse/homebridge-vivint] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://git.io/JtMGR for more info.

**Comment by 007GTCS** [comment]
Adding more logs to this. 
This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://git.io/JtMGR for more info.
(node:6051) UnhandledPromiseRejectionWarning: ReferenceError: log is not defined
    at /usr/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/garage_door.js:33:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6051) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6051) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by 007GTCS** [comment]
Also want to add, the status doesn't reflect open on the garage door. It will show a Garage Door Open Symbol, when first opened. But after you close out of the app. It will Show Closed symbol, but say open. Also It won't close sometimes because of this. 

node:8975) UnhandledPromiseRejectionWarning: ReferenceError: log is not defined
    at /usr/lib/node_modules/@balansse/homebridge-vivint/lib/accessories/garage_door.js:33:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:8975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

**Comment by balansse** [comment]
Thank you for reporting it! I will check it out next time I work on the plugin

**Comment by 007GTCS** [comment]
Thank You! No rush. Just wanted to point it out. Let me know if I can do anything to help!

**Comment by ethanbrown3** [comment]
I'm having the exact same issue. I can supply logs if it will help.
