### ISSUE TITLE
Cannot read property Panel ID

### ISSUE THREAD

**Issue by melvynray** [balansse/homebridge-vivint#46]
Bear with me. Literally learned all this overnight. Hoobs is horrible, so I wiped it and replaced with home bridge. What a world of difference. 

I finally got the Vivint plugin to work via Homebridge... almost.  This is the error in the log. (Please remember im a noob to all this, but learn quick) 

How can I fix it? 

[21/09/2021, 22:40:54] [@balansse/homebridge-vivint] Error while bootstrapping accessories: TypeError: Cannot read property 'PanelId' of undefined
    at Function.VivintApiModule.VivintApi.login (/usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/vivint_api.js:203:47)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by jgrimard** [comment]
@melvynray 
Did you figure out what was causing this error?  If so, what was it?
I think this would be caused by creating a user then disconnecting that user from the home.  So there would be a user to log in but the user wouldn't have access to a panel.
