### ISSUE TITLE
Plugin non-functional after Homebridge UI update

### ISSUE THREAD

**Issue by asander85** [balansse/homebridge-vivint#65]
I updated my Homebridge UI this morning to `version:homebridge-config-ui-x v4.46.0.` Now I get the following error message from the Vivint plugin:

`[6/7/2022, 8:33:52 AM] [@balansse/homebridge-vivint] Error while bootstrapping accessories: AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/src/lib/Accessory.ts:421:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/.pnpm/homebridge@1.4.1/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at Function.createDeviceAccessory (/var/lib/homebridge/node_modules/.pnpm/@balansse+homebridge-vivint@1.6.1/node_modules/@balansse/homebridge-vivint/lib/device_set.js:146:23)
    at /var/lib/homebridge/node_modules/.pnpm/@balansse+homebridge-vivint@1.6.1/node_modules/@balansse/homebridge-vivint/index.js:55:50
    at Array.map (<anonymous>)
    at /var/lib/homebridge/node_modules/.pnpm/@balansse+homebridge-vivint@1.6.1/node_modules/@balansse/homebridge-vivint/index.js:55:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
`

**Comment by balansse** [comment]
Looks like you have a device in Vivint that has an empty name - Nest thermostat integration caused it in the past - but it might be something else. I'll work on an update to handle this situation.
