### ISSUE TITLE
Slow To Respond

### ISSUE THREAD

**Issue by OspreyBoat** [balansse/homebridge-vivint#89]
Vivint BridgeERROR[Doorbell] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.

Other Error

PMVivint BridgeVivintERRORError getting system info: RequestError: Error: getaddrinfo EBUSY www.vivintsky.com
    at new RequestError (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/lib/hoobs/vivintbridge/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/var/lib/hoobs/vivintbridge/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: Error: getaddrinfo EBUSY www.vivintsky.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
    errno: -16,
    code: 'EBUSY',
    syscall: 'getaddrinfo',
    hostname: 'www.vivintsky.com'
  },
  error: Error: getaddrinfo EBUSY www.vivintsky.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
    errno: -16,
    code: 'EBUSY',
    syscall: 'getaddrinfo',
    hostname: 'www.vivintsky.com'
  },
  options: {
    url: 'https://www.vivintsky.com/api/systems/1673969479173966',
    headers: {
      Cookie: 's=ee1b4a6c-c1f3-4922-a5bb-1eb63f290d6c',
      'Cache-Control': 'no-store'
    },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

**Comment by jgrimard** [comment]
Please delete your cookie. It gives anyone full access to your alarm system and home address.

**Comment by OspreyBoat** [comment]
Thanks - put an XXXX there.

Perhaps I should delete the whole comment. But I wanted the developer to see something of the issue.

**Comment by jgrimard** [comment]
I would take a look but I don't have the doorbell camera. Just the basic alarm system.

**Comment by OspreyBoat** [comment]
Thanks - is my post at least safe now?

**Comment by jgrimard** [comment]
Yes, it looks fine to me.

**Comment by OspreyBoat** [comment]
Thanks and have a great weekend.  And thank you again for the cookie tip.
