### ISSUE TITLE
"The requested platform 'Vivint' was not registered by any plugin" after updating to the latest version?

### ISSUE THREAD

**Issue by alcallejas** [balansse/homebridge-vivint#9]
I just updated to the latest version (1.2.0) and now getting "The requested platform 'Vivint' was not registered by any plugin"

        {
            "username": "myemailaddress@mail.com",
            "password": "mypassword",
            "apiLoginRefreshSecs": 1200,
            "showCameraConfig": true,
            "platform": "Vivint"
        }

The error log says:

] Error: The requested platform 'Vivint' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
[10/13/2020, 00:14:57] Got SIGTERM, shutting down Homebridge

Any ideas what may have triggered this? I've tried to uninstall and reinstall using Homebridge Config UI X and no change.

**Comment by balansse** [comment]
Is that the only error message in the error log? Sounds like there should be another error, that prevents Vivint plugin to load.

**Comment by alcallejas** [comment]
Here's the only error I see:

[10/13/2020, 00:33:46] ====================
[10/13/2020, 00:33:46] ERROR LOADING PLUGIN @balansse/homebridge-vivint:
[10/13/2020, 00:33:46] Error: Cannot find module '../accessories/contact_sensor.js'
Require stack:
- /usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/device_set.js
- /usr/local/lib/node_modules/@balansse/homebridge-vivint/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@balansse/homebridge-vivint/lib/device_set.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
[10/13/2020, 00:33:46] ====================
[10/13/2020, 00:33:46] Loading 3 platforms...
[10/13/2020, 00:33:46] [Config] Initializing config platform...
[10/13/2020, 00:33:46] [Config] Running in Service Mode
[10/13/2020, 00:33:46] Error loading platform requested in your config.json at position 2
[10/13/2020, 00:33:46] Error: The requested platform 'Vivint' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)

**Comment by balansse** [comment]
Thank you for the detailed log! I’ll look into it tomorrow. You can
downgrade to the previous version in the meantime using:

npm install @balansse/homebridge-vivint@1.1.0

Where do you run your Homebridge instance?

**Comment by alcallejas** [comment]
Thanks, I run it on a Rasberry Pi3

Odd, when I try to install I get:

pi@raspberrypi:~ $ npm install @balansse/homebridge-vivint@1.1.0
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN @unimodules/react-native-adapter@5.6.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN @unimodules/react-native-adapter@5.6.0 requires a peer of react-native-web@~0.13.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-securerandom@0.1.1 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ @balansse/homebridge-vivint@1.1.0
updated 1 package and audited 311 packages in 7.086s

**Comment by balansse** [comment]
Try running npm install using sudo, it might help

**Comment by Jeffrey345678** [comment]
Worked fine for me until I rebooted home bridge trying to free up memory. Running on on a docker image within windows hypervisor. I downgraded it to 1.1.0 then updated back to 1.2.0. Rebooting home bridge again breaks it once again.

**Comment by alcallejas** [comment]
Are you getting the same "Error: Cannot find module '../accessories/contact_sensor.js” error?

**Comment by Jeffrey345678** [comment]
I'm not getting anywhere now. I was prompted to update npm and broke that now this is something ill have to resolve tomorrow. Dead on differential equations for the time being.

**Comment by balansse** [comment]
Looks like the accessory files were not included in the NPM package. Fixed that in 1.2.1

**Comment by alcallejas** [comment]
Just installed it, can confirm that fixed it. Thanks!

**Comment by Jeffrey345678** [comment]
[10/13/2020, 7:37:23 AM] [Vivint] Error while bootstrapping accessories: TypeError: Cannot read property 'Characteristic' of undefined
    at new Thermostat (/homebridge/node_modules/@balansse/homebridge-vivint/lib/accessories/thermostat.js:75:38)
    at DeviceSet.bindAccessory (/homebridge/node_modules/@balansse/homebridge-vivint/lib/device_set.js:40:20)
    at /homebridge/node_modules/@balansse/homebridge-vivint/index.js:81:27
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/@balansse/homebridge-vivint/index.js:79:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Now I'm having an issue with the thermostat. Disable thermostat and everything works!

**Comment by balansse** [comment]
> Now I'm having an issue with the thermostat. Disable thermostat and everything works!

Found the thermostat issue and fixed it in 1.2.2. Thank you for the detailed reports!
