### ISSUE TITLE
Can't get it to work anymore

### ISSUE THREAD

**Issue by cptgreedle** [balansse/homebridge-vivint#98]
This used to work really well for me, but a few months ago it just stopped responding to Vivint. I went through a lot of trouble getting it working again, but then it stopped shortly after. Every time it tries to run it gives me these errors in Hoobs:

``12/21/2022, 8:51:17 PMVivint BridgeVivintERRORError occured during login, retrying in 60 seconds... RequestError: Error: getaddrinfo EAI_AGAIN www.vivintsky.com
    at new RequestError (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/var/lib/hoobs/vivintbridge/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/lib/hoobs/vivintbridge/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/var/lib/hoobs/vivintbridge/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: Error: getaddrinfo EAI_AGAIN www.vivintsky.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'www.vivintsky.com'
  },
  error: Error: getaddrinfo EAI_AGAIN www.vivintsky.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'www.vivintsky.com'
  },
  options: {
    url: 'https://www.vivintsky.com/api/authuser',
    headers: { Cookie: 's=487e2ff6-0f06-45a9-b518-22b22f15f7be' },
    resolveWithFullResponse: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    transform2xxOnly: false
  },
  response: undefined
}
``

Ultimately I uninstalled it, with the intent to reinstall it, but now it says the plugin is not available:

```
2/21/2022, 8:58:15 PMWARNINGplugin site unavailable
12/21/2022, 8:58:16 PMyarn add v1.22.19
12/21/2022, 8:58:17 PM[1/4] Resolving packages...
12/21/2022, 8:58:17 PMerror An unexpected error occurred: "https://registry.yarnpkg.com/@balansse%2fhomebridge-vivint: getaddrinfo EAI_AGAIN registry.yarnpkg.com".
12/21/2022, 8:58:17 PMinfo If you think this is a bug, please open a bug report with the information provided in "/var/lib/hoobs/vivintbridge/yarn-error.log".
12/21/2022, 8:58:17 PMinfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Please help!

**Comment by jgrimard** [comment]
You may want to post this in HOOBS. The plugin has been working great for me in Homebridge.

**Comment by bzeeman** [comment]
You may also try creating a new user.
